import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Dashboard</title>
      </head>
      <body className={`font-system bg-gradient-bkg bg-bkg-color`}>
        {children}
      </body>
    </html>
  );
}
