version: '3'
networks:
  net:
    external: true

services:  
  spark:
    image: docker.io/bitnami/spark:3
    container_name: spark-master
    hostname: spark_master
    user: root
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
    ports:
      - '8080:8080'
    networks:  
      - net
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - net
  kafka:
    build: 
      context: .
      dockerfile: Dockerfile.kafka
    container_name: kafka
    hostname: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - net
    expose:
      - 9092
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - '9042:9042'
    networks:
      - net
  client:
    container_name: client
    image: ubuntu:jammy
    ports:
      - '9010:9010'
    networks:
      - net
    
